services:
  scouts-dentifrice:
    image: ghcr.io/e-was-here/dentifrice:1.0.0
    container_name: scouts-dentifrice
    working_dir: /app
    command: node server/server.js
    restart: unless-stopped
    volumes:
      - ./:/app
    environment:
      PORT: ${PORT}
      ADMIN_USER: ${ADMIN_USER:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      BASE_PATH: /dentifrice
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
